### ISSUE TITLE
Device recognises it is altered and halts some Google services

### ISSUE THREAD

**Issue by TJRegan** [LineageOS/android_device_oneplus_kebab#3]
Hey, I have an issue with the Google Play Store/Google Pay. The "Play Protect certification" in the Play Store settings shows as not-certified and Google Pay recognizes my device has been altered and therefore won't work. 

I'm using Lineage 2021/01/12 (with google services). **I am unrooted**, I believe this is due to the CTS profile showing as false. 

Thanks

**Comment by qnorsten** [comment]
I would say this is expected behaviour as LinageOS isn't certified by google, and as far as I know do not perform any signature spoofing either. 

if you want to pass the saftey net check and look Play protected certified you need to
1. Root with magisk
2.  Enable magisk hide (to pass basicintegrity) 
3. Install and use MagiskHide Props Config module to spoof your device fingerprint to a device that pass ctsProfile.
